---

- name: Install Docker dep packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  become: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker's official GPG key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker's apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu yakkety stable
    state: present
  become: true

- name: Install Docker
  apt:
    name: docker-ce
    state: installed
    update_cache: yes
  become: true

- name: Create docker group
  group:
    name: docker
    state: present
  become: true

- name: Add my user to the docker group
  user:
    name: oy
    append: yes
    groups: docker
  become: true
